version: 2

sources:
  - name: raw_data # This is the logical name used in DBT (you can choose this)
    database: dev # The actual database in Redshift
    schema: raw_data # The actual schema in Redshift
    tables:
      - name: orders_raw # Must match the actual table name in Redshift
      - name: order_items_raw
      - name: inventory_raw
      - name: customers_raw
      - name: dim_time
      - name: products_raw
      - name: stores_raw
      - name: employees_raw
  
   
